### PR TITLE
Fixed Issue #2 - Cheat Ring Sneak does nothing.

### PR DESCRIPTION
**Pull request by gir489**
Added a Lockpick ring.

### CODE REVIEW

**Comment by Bradenm1** [comment]
Alright, I'll take a look soon.

**Comment by gir489** [comment]
I'm also working on adding the imperial dragon set to the "supported mods" button, and making a Merchant that is available for trading in the cheat room that has infinite money, based on your script you're using with the containers, that would just add the money taken away when trading. The maximum amount of gold I've found a merchant can have is 65534. 32767 being in his normal container, and 32767 being in the merchant container they trade from. I'll make a pull request if I get it working.

**Comment by gir489** [comment]
Update on my progress. I've found the way you're doing the Supported Mods container is very slow, and sometimes causes Papyrus errors if I don't have the mod. I've refactored it completely to instead of using a button, it uses a persistent Quest that fires once when the mod is loaded (Or if you're updating, updating), then setups an OnPlayerLoadGame to refresh the list, so if you remove/add mods, it will automatically add the new items from the FormList.

So I removed the button that the user is required to press, and I've refactored the While loop to just do `containerToSpawn.AddItem(moddedItemsList)`. I've also made it add 1000 arrows for the Exoctic Arrows thing. I was getting tired of putting them in the cloner.

**Comment by gir489** [comment]
The Merchant is implemented and working as expected. There will have to be some explanation to the user via a button, but for the most part it works. Should be committing within a few hours after UX testing is complete.

**Comment by Bradenm1** [comment]
Do you use the mod often?

**Comment by gir489** [comment]
I do, actually. Pretty much every day. I made the Cheat Terminal for Fallout 4, so I thought maybe I could take a whack at improving the Cheat Room. I tried to make a terminal-like interface with the menus, and saw what tangled mess of callback hell that was going to be, I scrapped it. I'm glad you've done well with such limited resource and barely any UI.

**Comment by Bradenm1** [comment]
Nice, did you look at the Cheat Menu? It does work, but, it's overly complicated and I've never actually seen anyone use it. It's also missing a lot of commands and it has a few issues.

I don't use this mod myself, never have used it. A lot of things I've just thrown in because I thought people may use them. The room is just a cluster of random crap.

**Comment by gir489** [comment]
The room works quite well, I didn't know it came with a menu, using the storage boxes is a lot easier. The buttons on the wall also work quite well.

**Comment by Bradenm1** [comment]
It allowed you to use console commands, spawn modded things, teleport to cells, edit other actors, etc.
https://www.youtube.com/watch?v=g3sToeRdwFg&t
You can look through this cringe video and see it. That is as close as I could get to giving the player full control. Figure it may interest you if you've not seen it.

**Comment by gir489** [comment]
How are you able to execute console commands with Papyrus?

**Comment by Bradenm1** [comment]
It was not console commands, it was just papyrus functions, but it was pretty close since you could insert custom formIDs, strings, ints, floats using the menu into any function.

**Comment by gir489** [comment]
I ran in to some UX problems, and the bad memories of when I tried to make the cheat menu work in Skyrim are coming back... Once I've figured out a good solution I'll commit it.

**Comment by gir489** [comment]
Ran into a snag with the way containers work, I tried dumping all the items in to The Merchant's inventory and that seems to be a crap shoot if that works. So I'm reworking all the All Weapons/Ammo/Armor etc containers to be Leveled Items instead of containers with direct items in them. I don't know if there's a serious memory hit to doing this, I'd imagine it would be the same, just instead of loading the static list to memory it's loading the result of the leveled item to memory... Anyway, I've gotten Weapons and Ammo done, half of Armor done, and I should be finished either tomorrow or this weekend. There's a lot of items to add...

**Comment by Bradenm1** [comment]
What's the point in doing that if it works fine the way it is?

**Comment by gir489** [comment]
It just makes the containers more module that’s all. Also I think you made these containers prior to the DLC? I didn’t see the Dawnguard sword in the container. I added all the playable weapons that are in the game.

**Comment by gir489** [comment]
I found two problems.

1. CheatRoom_TheMerchant_Light_Gauntlets was missing from the CheatRoomMerchantButton script. That's easy to fix.
2. I can't upload the mod to Bethesda.net for testing, by clearing our my local files and then downloading the mod. It freezes as soon as I click PC then just closes.

There's some files in Meshes\Actors\Character\FaceGenData\FaceGeom\Cheat Room.esp that are not being added to the BSA when doing Create Archive. If I delete them from disk, the Merchant's face turns black.

**Comment by gir489** [comment]
I guess we have to manually add those three NIF files in the future.

**Comment by gir489** [comment]
I've completed integration testing for The Merchant. I would like you to do regression testing @Bradenm1 since I don't know how most of the room functions work. I don't think I touched anything, but you know how the Creation Kit is... It's embarrassing how many times I have to remove cell changes I swear I didn't make from the ESP. The problem with this, is there's no master to compare it to, so SSEEdit can't tell me if it's changed or not.

**Comment by Bradenm1** [comment]
I'm not sure when i'll get time this week, If I don't have time i'll have to look in the weekend.

**Comment by gir489** [comment]
I’m still doing integration testing for the merchant. I think I’ve fixed everything though.

**Comment by gir489** [comment]
Integration testing is complete, and I've even added the missing Creation Club mods to the Supported Mods list. The pull request is now ready for regression testing @Bradenm1 at your discretion.

**Comment by Bradenm1** [comment]
Alright, i'll test it today or tomorrow. I should have time.

**Comment by gir489** [comment]
If you’re confident in my abilities I would just merge it. But if you want to give it a once over that’s fine too. I’m mostly just worried about regression testing because I don’t know how things worked before my massive change. But I’m finding more things don’t work because they didn’t work at all in the first place like give all ingredients or remove all spells...

**Comment by gir489** [comment]
https://youtu.be/OCAVGy4MTRY

Fun.

**Comment by Bradenm1** [comment]
I did test it a couple days ago seems to be fine.

**Comment by Bradenm1** [comment]
It will have to wait. I will be able to around the 20th of next month.

**Comment by Bradenm1** [comment]
Sorry for the wait, I was unable to work on my mods due to certain things. I'll look into adding this tomorrow. Testing it and updating it.

:)

**Comment by Bradenm1** [comment]
What have you actually changed? It seems you've made changes you never listed.

**Comment by gir489** [comment]
@bradenm1 check the commit messages. Each commit should contain a separate change or individual changes.

**Comment by Bradenm1** [comment]
Hmm ok. It looks to be fine. I'll do a little more testing then merge it. I'll do the update for both PC and Xbox.

**Pull request merged**
